spring.application.name=ms-coincidencias
server.port=8085

# Apunta a db_mascotas para unificar los reportes
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/db_mascotas}
spring.datasource.username=postgres
spring.datasource.password=adminpassword123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Configuracion del Servidor de Mensajeria y Cache Remoto
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:localhost}
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=6379
# Permite que data.sql se ejecute despues de la creacion automatica de tablas
spring.jpa.defer-datasource-initialization=true