spring.application.name=ms-notificaciones
# 1. Cambiado a 8087 para calzar con Docker y liberar el puerto 8086 a ms-historial
server.port=8087

# 2. Correccion de la URL usando el contenedor real de tu ecosistema
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://sanos_y_salvos_postgres:5432/db_usuarios}
spring.datasource.username=postgres
spring.datasource.password=adminpassword123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# 3. Correccion del typo en la variable de RabbitMQ
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:sanos_y_salvos_rabbitmq}
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest