spring.application.name=ms-historial
server.port=8090

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/db_historial}
spring.datasource.username=postgres
spring.datasource.password=adminpassword123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ? Forzar la inyeccion de fichas medicas en modo update
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true