spring.application.name=ms-adopciones
server.port=8088

# Conexion Aislada a su Base de Datos Dedicada
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/db_adopciones}
spring.datasource.username=postgres
spring.datasource.password=adminpassword123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Enlace al Broker de Mensajeria
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:localhost}

# Permite que data.sql corra despues de que Hibernate cree las tablas
spring.jpa.defer-datasource-initialization=true