name: Deploy to Amazon EKS

on:
  push:
    branches:
      - main  # O la rama por defecto que tengas en tu repositorio

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: innovatech-frontend
  EKS_CLUSTER_NAME: eks-cluster

jobs:
  deploy:
    name: Build, Push and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ASIAST6FMTD2YBW7AZ3G
          aws-secret-access-key: 4qwiScKmndqWsJMqHbyX3AxRo0yi680hHIPa/zKc
          aws-session-token: IQoJb3JpZ2luX2VjEEwaCXVzLXdlc3QtMiJIMEYCIQCxSvVIukk5BZRrqjai47uJwWtrqTsEm+CIWJ409i4KNAIhAMfQoIeGfjm3VUG65AFLrJcbEWI1P2jq+t/YC7B4oCYmKq0CCBUQABoMMTgwMjY1NzIwMDUzIgzhE4qGZVR4a+CxzmoqigKKSBdFqlrmlgRKRFCv4ERKfF/S9PkSLEITd747n278r+GVcm2YpgF+YH3j7EL+SyDemy+J9Ilbi2zbQ1VubDFy1Ihx+kfGZHmsVYtUSt1hQcUntr2qzcH1nHp/I+FXQelr1EiD2LTxYQhf18wg9UL+6zpY2AM2U623sfKHcVTp8MxtQvma0TyHh81coizK5CJjMsV44FAzmGboeO8lme/VFfQ5D+VuLugDFrRiAr16T2fo3TN6uN0o2GpE84Vrk36YdrNE/vuNSY8cIVI/IYlrcHHcp7Qzt6hVaTYWKmvwMm3inF6sqPMbMVUa/gdfx+TyUnYgAxKa0nqYVcnmpMNK/VZW3YwOdMJk9TCWgujRBjqcAUl1AN6c/OBeD65T5hCMod0G1cJMxuQLLZXrdsZuvy6beuu8Xbvfi+8qlimzoPv6J3CHMfIQufgyNYovOp1zeQ6hOR4AJmS22Jt/Wo2xL6kDswzSgYN18AL4QLGP/ZJ5bu5d2ixBD3gHd+8xmYnfSsNvmQIVCFP2SB72qHyhh8eJgjDjynoiiCUZkfQgoYUtNkGEifzny2zn0RSIkg==
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, Tag, and Push Image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Update Kubeconfig
        run: |
          aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER_NAME }} --region ${{ env.AWS_REGION }}

      - name: Deploy to EKS
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Reemplaza la etiqueta de la imagen dinámicamente en tu archivo front.yml
          sed -i "s|\${IMAGE_TAG}|$IMAGE_TAG|g" front.yml
          kubectl apply -f front.yml
